CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL
);

CREATE TABLE Orders (
    Id INT PRIMARY KEY IDENTITY(1,1)
);

CREATE TABLE Products (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Height INT NOT NULL,
    Width INT NOT NULL,
    Length INT NOT NULL,
    OrderId INT NOT NULL,
    CONSTRAINT FK_Products_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
);

CREATE TABLE Boxes (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Type NVARCHAR(100) NOT NULL,
    Height INT NOT NULL,
    Width INT NOT NULL,
    Length INT NOT NULL,
    OrderId INT NOT NULL,
    TypeBox NVARCHAR(100) NULL,
    CONSTRAINT FK_Boxes_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
);
