services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ConnecTion@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P ConnecTion@123 -Q 'SELECT 1'" ]
      interval: 10s
      retries: 5

  app:
    build:
      context: ./GameStore
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__SqlConnection=Server=db;Database=GameStore;User Id=sa;Password=ConnecTion@123;
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped

volumes:
  sqlserverdata:
  dataprotection-keys:
